spring.application.name=kiosks-core

server.port=8090

spring.datasource.url=jdbc:postgresql://localhost:5432/kiosks_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

spring.jackson.serialization.fail-on-empty-beans=false
